
FLAGS = -Wall -Wextra -Werror -std=c11
Targets = print_module.c main_module_entry_point.c

OUT = Quest_1
DIR_OUT = ../build/

all: print_module

print_module: $(Targets)
	gcc $(FLAGS) $^ -o $(DIR_OUT)$(OUT)